importing the dependencies

In [92]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [94]:
df=pd.read_csv('creditcard.csv.zip')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [96]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

dataset informations

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

checking the number of missing values in each column

In [102]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [104]:
print(df['Class'].value_counts())

Class
0    284315
1       492
Name: count, dtype: int64

fraud=1 ,legit=0

In [107]:
print(df.describe())

                Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000

               Class
count  284807.000000
mean        0.001727
std         0.041527
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

[8 rows x 31 columns]

In [109]:
legit=df[df.Class==0]
fraud=df[df.Class==1]

In [111]:
print(fraud.head())

        Time        V1        V2        V3        V4        V5        V6  \
541    406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920  4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788
6108  6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536
6329  7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746

            V7        V8        V9  ...       V21       V22       V23  \
541  -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211
623   0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966
4920  0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726
6108 -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207
6329  1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805

           V24       V25       V26       V27       V28  Amount  Class
541   0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1
623  -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1
4920 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93      1
6108 -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00      1
6329 -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00      1

[5 rows x 31 columns]

In [113]:
new_df= legit.sample(n=492)

In [115]:
print(new_df.head())

           Time        V1        V2        V3        V4        V5        V6  \
149841  92047.0 -1.256190  1.035857  1.427818 -0.525712  0.357855  0.230287
108631  70999.0 -6.564508 -1.416958 -1.707006  1.442271 -1.861757 -0.654997
117067  74526.0  1.009097  0.008646  1.171783  2.782552 -0.798571  0.042604
137582  82230.0  1.256199 -0.015231 -1.469229 -0.093911  2.128520  3.459439
98414   66653.0 -1.146346 -0.031043  1.753851 -3.238376 -0.860179 -0.901278

              V7        V8        V9  ...       V21       V22       V23  \
149841  0.130913  0.471056  1.035923  ... -0.376938 -0.911007 -0.233028
108631 -0.298253  1.304146  0.131099  ... -0.683448  0.010468  1.264737
117067 -0.377298  0.132099  0.140504  ...  0.096669  0.262457 -0.139143
137582 -0.660356  0.902599  0.461278  ... -0.234142 -0.584964 -0.130329
98414   0.228732  0.084347  0.353739  ... -0.630123 -1.026195 -0.081713

             V24       V25       V26       V27       V28  Amount  Class
149841 -1.115645  0.453346  0.156741  0.110357  0.016760   35.00      0
108631  0.543971  0.341083  0.247675 -1.067383 -0.422441  127.84      0
117067  0.396660  0.476423  0.145488  0.011098  0.037544   69.35      0
137582  0.941959  0.706134  0.426656  0.003528  0.036224   12.31      0
98414   0.352130  0.395935 -0.269799  0.408802  0.202796   30.00      0

[5 rows x 31 columns]

In [117]:
new_df=pd.concat([new_df, fraud],axis=0)

In [119]:
print(new_df.shape)

(984, 31)

In [121]:
X= new_df.drop(columns=['Amount'],axis=1)

In [123]:
y=new_df['Amount']

In [125]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
print(X_train.head())

            Time        V1        V2        V3        V4        V5        V6  \
217155  140789.0 -1.066909 -0.588967  0.774322 -1.450180 -0.926548  0.096485
224451  143797.0  1.915794 -0.156173 -1.007981  0.421185 -0.145240 -0.402300
245347  152710.0  0.051075  1.310427  0.733222  2.620282  1.402358  0.528489
243393  151916.0 -5.488032  3.329561 -5.996296  3.601720 -2.023926 -1.737393
161720  114457.0 -0.912298  1.201845  0.605604  2.348474  1.915996  0.459886

              V7        V8        V9  ...       V20       V21       V22  \
217155  0.020311  0.552838 -1.270894  ...  0.486203  0.067322 -0.404204
224451 -0.378587  0.045165  0.928337  ... -0.106747 -0.255851 -0.679583
245347  1.086014 -0.146423 -1.724333  ... -0.125877  0.229936  0.766927
243393 -4.396859  0.228394 -1.675884  ... -0.551121  1.719631  0.343209
161720  0.809114  0.111537 -1.946009  ... -0.337490  0.313740  0.680800

             V23       V24       V25       V26       V27       V28  Class
217155  0.431188 -0.451765 -0.380593 -0.495664 -0.040276  0.025338      0
224451  0.276723 -0.647018 -0.412903 -0.655738  0.035764 -0.014461      0
245347 -0.189624  0.766853 -0.141401 -0.077278 -0.297595 -0.221816      1
243393  0.133584  0.833340 -0.839776  0.502010 -1.937473  1.521218      1
161720 -0.437602  0.169965  0.013425  0.050058 -0.144969  0.166415      0

[5 rows x 30 columns]

In [127]:
print(y_train.head())

217155    189.60
224451     35.42
245347      2.47
243393      0.01
161720      7.57
Name: Amount, dtype: float64

In [147]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
149841   92047.0 -1.256190  1.035857  1.427818 -0.525712  0.357855  0.230287
108631   70999.0 -6.564508 -1.416958 -1.707006  1.442271 -1.861757 -0.654997
117067   74526.0  1.009097  0.008646  1.171783  2.782552 -0.798571  0.042604
137582   82230.0  1.256199 -0.015231 -1.469229 -0.093911  2.128520  3.459439
98414    66653.0 -1.146346 -0.031043  1.753851 -3.238376 -0.860179 -0.901278
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
149841  0.130913  0.471056  1.035923  ...  0.156998 -0.376938 -0.911007
108631 -0.298253  1.304146  0.131099  ... -3.277375 -0.683448  0.010468
117067 -0.377298  0.132099  0.140504  ... -0.089703  0.096669  0.262457
137582 -0.660356  0.902599  0.461278  ...  0.048465 -0.234142 -0.584964
98414   0.228732  0.084347  0.353739  ... -0.337212 -0.630123 -1.026195
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Class
149841 -0.233028 -1.115645  0.453346  0.156741  0.110357  0.016760      0
108631  1.264737  0.543971  0.341083  0.247675 -1.067383 -0.422441      0
117067 -0.139143  0.396660  0.476423  0.145488  0.011098  0.037544      0
137582 -0.130329  0.941959  0.706134  0.426656  0.003528  0.036224      0
98414  -0.081713  0.352130  0.395935 -0.269799  0.408802  0.202796      0
...          ...       ...       ...       ...       ...       ...    ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968      1
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637      1
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361      1
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700      1
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309      1

[984 rows x 30 columns]

In [149]:
print(y)

149841     35.00
108631    127.84
117067     69.35
137582     12.31
98414      30.00
           ...
279863    390.00
280143      0.76
280149     77.89
281144    245.00
281674     42.53
Name: Amount, Length: 984, dtype: float64

In [161]:
print(X.shape, X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

model training

In [210]:
model= LogisticRegression()

model evaluation,
(accuracy score)